### ISSUE TITLE
change the API hanime to this api

### ISSUE THREAD

**Issue by Fandyfr** [Streamsora/streamsora#5]
New API Hanime: https://hanime-api-plum.vercel.app
Old API : https://hanime-api-five.vercel.app

**Comment by Zinedinarnaut** [comment]
I'll be hosting the hanime api on my own server I'll fix all of that up

**Comment by Fandyfr** [comment]
okay, because I have your code which is streamsora v1 and v2 and I fixed it too.

**Comment by Zinedinarnaut** [comment]
We only work on this one, I'm planning on removing the the other one

**Comment by Fandyfr** [comment]
You didn't continue streamsora v2 even though it was good from the UI.
I fixed the code both from the API Hanime & AniList.

**Comment by Zinedinarnaut** [comment]
We migrated from js to ts as it's more flexible and there's much more we can do rather it being in js

**Comment by Fandyfr** [comment]
Can I take the streamsora v2?

**Comment by Zinedinarnaut** [comment]
I mean sure you gotta follow the licence as well
